cmake_minimum_required(VERSION 3.28)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  project(linking_app LANGUAGES CXX ASM)
endif()
include(SymbianApp)
symbian_add_dynamic_library(linking_dynamic SOURCES dynamic.cc UID3 0xe0000e06)
target_include_directories(linking_dynamic PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
symbian_add_static_library(linking_static SOURCES static.cc)
target_include_directories(linking_static PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(linking_static PUBLIC linking_dynamic)
symbian_add_executable(linking_app app.cc)
target_link_libraries(linking_app PRIVATE linking_static)
symbian_publish_executable(linking_app UID3 0xe0000e05 PROJECT_DLLS BUNDLE)
