# Stage exactly the project DLLs recorded by the SDK's evaluated target graph.
cmake_minimum_required(VERSION 3.28)
file(READ "${GRAPH_FILE}" graph)
string(JSON schema GET "${graph}" schema)
if(NOT schema STREQUAL "symbian.application-libraries/v1")
  message(FATAL_ERROR "Unknown application DLL graph: ${GRAPH_FILE}")
endif()
string(JSON count LENGTH "${graph}" libraries)
set(records "[]")
set(names)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}/libraries")
if(count GREATER 0)
  math(EXPR last "${count} - 1")
  foreach(index RANGE 0 ${last})
    string(JSON image GET "${graph}" libraries ${index})
    get_filename_component(name "${image}" NAME)
    string(TOLOWER "${name}" name_key)
    if(name_key IN_LIST names OR NOT name MATCHES "^[A-Za-z0-9_-]+\\.dll$")
      message(FATAL_ERROR "Duplicate or invalid application DLL name: ${name}")
    endif()
    list(APPEND names "${name_key}")
    file(SHA256 "${image}" digest)
    file(COPY_FILE "${image}" "${OUTPUT_DIRECTORY}/libraries/${name}" ONLY_IF_DIFFERENT)
    string(JSON record SET "{}" file "\"libraries/${name}\"")
    string(JSON record SET "${record}" sha256 "\"${digest}\"")
    string(JSON records SET "${records}" ${index} "${record}")
  endforeach()
endif()
file(WRITE "${OUTPUT_DIRECTORY}/${TARGET_NAME}.libraries.json"
  "{\"schema\":\"symbian.application-payload/v1\",\"libraries\":${records}}\n")
