# Original Symbian GLES 1.1 Common, GLES 2.0 and EGL 1.4 import contracts.
include_guard(GLOBAL)
set(SYMBIAN_GRAPHICS_AVAILABLE_APIS "EGL;GLES1;GLES2" CACHE STRING
  "Graphics APIs supplied by the deployment firmware; empty disables graphics")
set(SYMBIAN_GRAPHICS_FIRMWARE_DIR "" CACHE PATH
  "Optional deployment Z-drive directory; required graphics DLLs are checked at configure time")
foreach(pair IN ITEMS "GLES1:libglesv1_cm:GLES/gl.h"
    "GLES2:libglesv2:GLES2/gl2.h" "EGL:libegl:EGL/egl.h")
  string(REPLACE ":" ";" fields "${pair}")
  list(GET fields 0 api)
  list(GET fields 1 dll)
  list(GET fields 2 header)
  set(proxy "${SYMBIAN_SDK_PREFIX}/proxies/${dll}/${dll}.dso")
  get_filename_component(header_directory "${header}" DIRECTORY)
  if(api STREQUAL "GLES1")
    set(headers gl.h glext.h glplatform.h glextplatform.h egl.h egltypes.h
      legacy_egl_1_1/egl.h legacy_egl_1_1/egltypes.h)
  elseif(api STREQUAL "GLES2")
    set(headers gl2.h gl2ext.h gl2platform.h gl2extplatform.h)
  else()
    set(headers egl.h egltypes.h eglext.h khronos_types.h)
  endif()
  set(required "${proxy};${SYMBIAN_SDK_PREFIX}/include/platform/e32def.h")
  foreach(required_header IN LISTS headers)
    list(APPEND required
      "${SYMBIAN_SDK_PREFIX}/include/graphics/${header_directory}/${required_header}")
  endforeach()
  if(api STREQUAL "EGL")
    list(APPEND required "${SYMBIAN_SDK_PREFIX}/include/graphics/KHR/khrplatform.h")
  endif()
  add_library(SymbianGraphics${api} INTERFACE)
  add_library(Symbian::${api} ALIAS SymbianGraphics${api})
  set_target_properties(SymbianGraphics${api} PROPERTIES
    SYMBIAN_GRAPHICS_API "${api}"
    SYMBIAN_GRAPHICS_DLL "${dll}.dll"
    SYMBIAN_GRAPHICS_FILES "${required}")
  # Keep unavailable targets nameable so the deferred checker can diagnose
  # the actual consumer, even through static/interface dependencies.
  if(EXISTS "${proxy}" AND EXISTS "${SYMBIAN_SDK_PREFIX}/include/graphics/${header}")
    target_link_libraries(SymbianGraphics${api} INTERFACE "${proxy}" Symbian::EUser)
    target_include_directories(SymbianGraphics${api} SYSTEM INTERFACE
      "${SYMBIAN_SDK_PREFIX}/include/graphics")
    target_compile_options(SymbianGraphics${api} INTERFACE
      -fdeclspec -Wno-ignored-attributes)
    target_compile_definitions(SymbianGraphics${api} INTERFACE __SYMBIAN32__)
  endif()
endforeach()

# Inspect each consumer once, retaining graph nodes for ABI flag validation.
# Conditional links outside LINK_ONLY/BUILD_INTERFACE are deliberately rejected
# in graphics graphs: CMake cannot evaluate arbitrary link genex at configure
# time. An explicit if() gives a concrete graph and an early useful diagnostic.
function(_symbian_graphics_walk target mode)
  get_property(seen GLOBAL PROPERTY SYMBIAN_GRAPHICS_WALK)
  get_target_property(alias ${target} ALIASED_TARGET)
  if(alias)
    set(target "${alias}")
  endif()
  if(target IN_LIST seen)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY SYMBIAN_GRAPHICS_WALK "${target}")
  get_target_property(type ${target} TYPE)
  foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
    # A DLL's private graphics imports bind in that DLL, not its consumers.
    # Validate its implementation separately as a root of its own graph.
    if(property STREQUAL "LINK_LIBRARIES" AND type STREQUAL "SHARED_LIBRARY"
       AND NOT mode STREQUAL "ROOT")
      continue()
    endif()
    get_target_property(items ${target} ${property})
    foreach(item IN LISTS items)
      if(item MATCHES "^\\$<(LINK_ONLY|BUILD_INTERFACE):([^<>]+)>$")
        set(item "${CMAKE_MATCH_2}")
      elseif(item MATCHES "\\$<")
        set_property(GLOBAL APPEND PROPERTY SYMBIAN_GRAPHICS_CONDITIONAL "${item}")
        # Discover targets hidden inside an expression, then reject only if
        # this graph actually uses graphics. No silent skipped validation.
        string(REGEX MATCHALL "[A-Za-z_][A-Za-z0-9_:.-]*" candidates "${item}")
        foreach(candidate IN LISTS candidates)
          if(TARGET "${candidate}")
            _symbian_graphics_walk("${candidate}" CHILD)
          endif()
        endforeach()
      endif()
      if(TARGET "${item}")
        _symbian_graphics_walk("${item}" CHILD)
      endif()
    endforeach()
  endforeach()
endfunction()

function(_symbian_validate_graphics target)
  get_target_property(own_api ${target} SYMBIAN_GRAPHICS_API)
  if(own_api)
    return()
  endif()
  set_property(GLOBAL PROPERTY SYMBIAN_GRAPHICS_WALK "")
  set_property(GLOBAL PROPERTY SYMBIAN_GRAPHICS_CONDITIONAL "")
  _symbian_graphics_walk(${target} ROOT)
  get_property(nodes GLOBAL PROPERTY SYMBIAN_GRAPHICS_WALK)
  set(apis)
  foreach(node IN LISTS nodes)
    get_target_property(api ${node} SYMBIAN_GRAPHICS_API)
    if(api)
      list(APPEND apis "${api}")
      if(NOT api IN_LIST SYMBIAN_GRAPHICS_AVAILABLE_APIS)
        message(FATAL_ERROR "${target}: Symbian::${api} is unavailable in SYMBIAN_GRAPHICS_AVAILABLE_APIS (deployment firmware)")
      endif()
      get_target_property(files ${node} SYMBIAN_GRAPHICS_FILES)
      foreach(file IN LISTS files)
        if(NOT EXISTS "${file}")
          message(FATAL_ERROR "${target}: Symbian::${api} is unavailable: missing SDK file ${file}. Update or prepare the SDK.")
        endif()
      endforeach()
      if(SYMBIAN_GRAPHICS_FIRMWARE_DIR)
        get_target_property(dll ${node} SYMBIAN_GRAPHICS_DLL)
        file(GLOB firmware_dlls
          "${SYMBIAN_GRAPHICS_FIRMWARE_DIR}/sys/bin/*"
          "${SYMBIAN_GRAPHICS_FIRMWARE_DIR}/Sys/Bin/*")
        set(found FALSE)
        foreach(candidate IN LISTS firmware_dlls)
          get_filename_component(filename "${candidate}" NAME)
          string(TOLOWER "${filename}" filename)
          if(filename STREQUAL dll)
            set(found TRUE)
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${candidate}")
          endif()
        endforeach()
        if(NOT found)
          message(FATAL_ERROR "${target}: Symbian::${api} is unavailable in selected firmware: missing ${dll} under ${SYMBIAN_GRAPHICS_FIRMWARE_DIR}/sys/bin")
        endif()
      endif()
    endif()
  endforeach()
  if(NOT apis)
    return()
  endif()
  get_property(conditional GLOBAL PROPERTY SYMBIAN_GRAPHICS_CONDITIONAL)
  if(conditional)
    message(FATAL_ERROR "${target}: graphics link graph uses unsupported conditional links: ${conditional}. Select dependencies with CMake if() so they can be checked at configuration time.")
  endif()
  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Generic" OR
      NOT SYMBIAN_TARGET_ARCH MATCHES "^(armv5t|armv6)$" OR
      NOT CMAKE_CXX_COMPILER_TARGET STREQUAL "${SYMBIAN_TARGET_ARCH}-none-eabi")
    message(FATAL_ERROR "${target}: Symbian graphics requires the Symbian ARM EABI toolchain, armv5t or armv6")
  endif()
  if("GLES1" IN_LIST apis AND "GLES2" IN_LIST apis)
    message(FATAL_ERROR "${target}: direct GLES1 and GLES2 imports overlap. Link one GLES API per binary; use EGL procedure lookup for multiple context APIs.")
  endif()
  set(options "${CMAKE_C_FLAGS};${CMAKE_CXX_FLAGS};${CMAKE_EXE_LINKER_FLAGS};${CMAKE_SHARED_LINKER_FLAGS}")
  set(configs Debug Release RelWithDebInfo MinSizeRel ${CMAKE_CONFIGURATION_TYPES} ${CMAKE_BUILD_TYPE})
  foreach(config IN LISTS configs)
    string(TOUPPER "${config}" config)
    list(APPEND options "${CMAKE_C_FLAGS_${config}}" "${CMAKE_CXX_FLAGS_${config}}")
    list(APPEND options "${CMAKE_EXE_LINKER_FLAGS_${config}}"
      "${CMAKE_SHARED_LINKER_FLAGS_${config}}")
  endforeach()
  foreach(node IN LISTS nodes)
    get_target_property(kernel ${node} SYMBIAN_IMAGE_KERNEL)
    if(kernel STREQUAL "eka1")
      message(FATAL_ERROR "${target}: these Symbian graphics imports require EKA2; EKA1 is unavailable")
    endif()
    foreach(property COMPILE_OPTIONS INTERFACE_COMPILE_OPTIONS LINK_OPTIONS INTERFACE_LINK_OPTIONS
                     COMPILE_DEFINITIONS INTERFACE_COMPILE_DEFINITIONS COMPILE_FLAGS LINK_FLAGS)
      get_target_property(value ${node} ${property})
      list(APPEND options ${value})
    endforeach()
    get_target_property(sources ${node} SOURCES)
    get_target_property(directory ${node} SOURCE_DIR)
    foreach(source IN LISTS sources)
      if(NOT source MATCHES "\\$<")
        get_source_file_property(value "${source}" DIRECTORY "${directory}" COMPILE_OPTIONS)
        list(APPEND options ${value})
        get_source_file_property(value "${source}" DIRECTORY "${directory}" COMPILE_FLAGS)
        list(APPEND options ${value})
        get_source_file_property(value "${source}" DIRECTORY "${directory}" COMPILE_DEFINITIONS)
        list(APPEND options ${value})
      endif()
    endforeach()
  endforeach()
  string(REGEX MATCHALL "-march[= ][A-Za-z0-9_.+-]+" architecture_flags "${options}")
  foreach(flag IN LISTS architecture_flags)
    string(REGEX REPLACE "^-march[= ]" "" architecture "${flag}")
    if(NOT architecture STREQUAL SYMBIAN_TARGET_ARCH)
      message(FATAL_ERROR "${target}: graphics architecture flag ${flag} conflicts with SYMBIAN_TARGET_ARCH=${SYMBIAN_TARGET_ARCH}")
    endif()
  endforeach()
  if("${options}" MATCHES "-mcpu[= ]")
    message(FATAL_ERROR "${target}: graphics CPU overrides are unavailable; select SYMBIAN_TARGET_ARCH=armv5t or armv6 instead of -mcpu")
  endif()
  string(REGEX MATCHALL "-mfpu[= ][A-Za-z0-9_.+-]+" fpu_flags "${options}")
  foreach(flag IN LISTS fpu_flags)
    if(NOT flag MATCHES "-mfpu[= ]none$")
      message(FATAL_ERROR "${target}: graphics requires the SDK software floating-point profile; incompatible FPU flag ${flag}")
    endif()
  endforeach()
  if("${options}" MATCHES "-mfloat-abi[= ](hard|softfp)|-mabi[= ](apcs-gnu|aapcs-vfp)|-fno-short-wchar")
    message(FATAL_ERROR "${target}: graphics requires soft-float AAPCS and 16-bit wchar_t; incompatible ABI flags: ${options}")
  endif()
  if("${options}" MATCHES "__OPENGLESHEADERS_LEGACY_EGL_1_1|SYMBIAN_OGLES_DLL_EXPORTS")
    message(FATAL_ERROR "${target}: graphics import targets require the system EGL headers and client declarations; legacy EGL 1.1/vendor export flags are incompatible")
  endif()
endfunction()

function(_symbian_validate_graphics_directory directory)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  foreach(target IN LISTS targets)
    _symbian_validate_graphics(${target})
  endforeach()
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    _symbian_validate_graphics_directory("${child}")
  endforeach()
endfunction()
cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}"
  CALL _symbian_validate_graphics_directory "${CMAKE_SOURCE_DIR}")
