# Inventory-backed original public native APIs. No firmware implementations.
include_guard(GLOBAL)

function(symbian_enable_native_leaves target)
  target_compile_definitions(${target} PRIVATE SYMBIAN_NATIVE_LEAVES=1)
  cmake_parse_arguments(PARSE_ARGV 1 LEAVES "" "" "SOURCES")
  if(LEAVES_UNPARSED_ARGUMENTS OR NOT LEAVES_SOURCES)
    message(FATAL_ERROR "symbian_enable_native_leaves needs SOURCES: select the native leave boundary explicitly")
  endif()
  foreach(source IN LISTS LEAVES_SOURCES)
    set_property(SOURCE "${source}" APPEND PROPERTY COMPILE_OPTIONS
      -fexceptions -frtti)
    set_property(SOURCE "${source}" APPEND PROPERTY COMPILE_DEFINITIONS
      __SUPPORT_CPP_EXCEPTIONS__ __LEAVE_EQUALS_THROW__)
  endforeach()
  target_link_libraries(${target} PRIVATE Symbian::CxxAbi)
  # A proxy carries ordinals, never the bytes of a firmware type-info object.
  target_link_options(${target} PRIVATE "SHELL:-z nocopyreloc" "SHELL:-z notext"
    "--undefined=symbian_native_leave_personalities")
  target_sources(${target} PRIVATE
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/native_leave_personality.S"
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/native_leave_personality.cc")
endfunction()
set(native_inventory "${SYMBIAN_SDK_PREFIX}/share/symbian/native/inventory.json")
if(NOT EXISTS "${native_inventory}")
  return()
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${native_inventory}")
file(READ "${native_inventory}" native_surface)
set(SYMBIAN_NATIVE_FIRMWARE_DIR "" CACHE PATH
  "Optional complete deployment Z-drive; native DLL presence is checked")
add_library(SymbianNativeAbi INTERFACE)
target_include_directories(SymbianNativeAbi SYSTEM INTERFACE
  "${SYMBIAN_SDK_PREFIX}/include/native"
  "${SYMBIAN_SDK_PREFIX}/include/platform"
  "${SYMBIAN_SDK_PREFIX}/include/graphics")
# Original C headers must follow the selected libc++ profile. In particular,
# libc++'s stddef.h wrapper has to precede Open C's stddef.h in a modern app.
foreach(directory compiler openc libc libm pthread posix4 native/stdapis
    native/stdapis/glib-2.0)
  target_compile_options(SymbianNativeAbi INTERFACE
    "SHELL:-idirafter \"${SYMBIAN_SDK_PREFIX}/include/${directory}\"")
endforeach()
target_compile_definitions(SymbianNativeAbi INTERFACE
  _UNICODE __GCC32__ __GCCV3__ __EABI__ __EPOC32__ __MARM__ __MARM_ARMV5__
  __SYMBIAN32__ __LONG_LONG_SUPPORTED SYMBIAN_CAF_V2)
target_compile_options(SymbianNativeAbi INTERFACE
  -fshort-wchar -fdeclspec -Wno-ignored-attributes)
string(JSON count LENGTH "${native_surface}" facilities)
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
  string(JSON entry GET "${native_surface}" facilities ${index})
  string(JSON name GET "${entry}" target)
  string(JSON dll GET "${entry}" dll)
  string(JSON blocked ERROR_VARIABLE available GET "${entry}" blocked)
  string(REGEX REPLACE "\\.dll$" "" basename "${dll}")
  set(proxy "${SYMBIAN_SDK_PREFIX}/proxies/${basename}/${basename}.dso")
  add_library(SymbianNative${name} INTERFACE)
  add_library(Symbian::${name} ALIAS SymbianNative${name})
  set_target_properties(SymbianNative${name} PROPERTIES
    SYMBIAN_NATIVE_API "${name}" SYMBIAN_NATIVE_DLL "${dll}"
    SYMBIAN_NATIVE_ENTRY "${entry}")
  target_link_libraries(SymbianNative${name} INTERFACE SymbianNativeAbi Symbian::EUser)
  if(available)
    # Every selected definition retains the complete frozen ordinal table.
    target_link_libraries(SymbianNative${name} INTERFACE "${proxy}")
    string(JSON ms_extensions ERROR_VARIABLE no_ms_extensions GET "${entry}" ms_extensions)
    if(ms_extensions AND NOT no_ms_extensions)
      # Original Nokia headers contain redundantly qualified member names.
      target_compile_options(SymbianNative${name} INTERFACE
        -fms-extensions -Wno-microsoft-extra-qualification)
    endif()
    if(name STREQUAL "OpenVG" OR name STREQUAL "OpenVGU")
      target_compile_definitions(SymbianNative${name} INTERFACE
        __OPENVGHEADERS_USE_VG_1_1)
    endif()
  else()
    set_property(TARGET SymbianNative${name} PROPERTY SYMBIAN_NATIVE_BLOCKED "${blocked}")
  endif()
endforeach()
foreach(index RANGE 0 ${last})
  string(JSON entry GET "${native_surface}" facilities ${index})
  string(JSON name GET "${entry}" target)
  string(JSON count LENGTH "${entry}" dependencies)
  if(count GREATER 0)
    math(EXPR dependency_last "${count} - 1")
    foreach(dependency_index RANGE 0 ${dependency_last})
      string(JSON dependency GET "${entry}" dependencies ${dependency_index})
      target_link_libraries(SymbianNative${name} INTERFACE Symbian::${dependency})
    endforeach()
  endif()
endforeach()

function(_symbian_validate_native target)
  get_target_property(own_api ${target} SYMBIAN_NATIVE_API)
  if(own_api)
    return()
  endif()
  # Share the existing traversal semantics, including private DLL boundaries.
  set_property(GLOBAL PROPERTY SYMBIAN_GRAPHICS_WALK "")
  set_property(GLOBAL PROPERTY SYMBIAN_GRAPHICS_CONDITIONAL "")
  _symbian_graphics_walk(${target} ROOT)
  get_property(nodes GLOBAL PROPERTY SYMBIAN_GRAPHICS_WALK)
  set(apis)
  foreach(node IN LISTS nodes)
    get_target_property(api ${node} SYMBIAN_NATIVE_API)
    if(NOT api)
      continue()
    endif()
    list(APPEND apis "${api}")
    get_target_property(blocked ${node} SYMBIAN_NATIVE_BLOCKED)
    if(blocked)
      message(FATAL_ERROR "${target}: Symbian::${api} is blocked: ${blocked}. See share/symbian/native/inventory.json for source/version evidence.")
    endif()
    get_target_property(entry ${node} SYMBIAN_NATIVE_ENTRY)
    get_target_property(dll ${node} SYMBIAN_NATIVE_DLL)
    string(REGEX REPLACE "\\.dll$" "" basename "${dll}")
    set(required "${SYMBIAN_SDK_PREFIX}/proxies/${basename}/${basename}.dso")
    string(JSON definition GET "${entry}" definition destination)
    list(APPEND required "${SYMBIAN_SDK_PREFIX}/${definition}")
    string(JSON count LENGTH "${entry}" headers)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
      string(JSON header GET "${entry}" headers ${index})
      list(APPEND required "${SYMBIAN_SDK_PREFIX}/include/native/${header}")
    endforeach()
    string(JSON closure_count ERROR_VARIABLE no_closure LENGTH "${entry}" header_payloads)
    if(NOT no_closure AND closure_count GREATER 0)
      math(EXPR closure_last "${closure_count} - 1")
      foreach(index RANGE 0 ${closure_last})
        string(JSON payload GET "${entry}" header_payloads ${index})
        list(APPEND required "${SYMBIAN_SDK_PREFIX}/${payload}")
      endforeach()
    endif()
    foreach(file IN LISTS required)
      if(NOT EXISTS "${file}")
        message(FATAL_ERROR "${target}: Symbian::${api} is unavailable: missing SDK payload ${file}. Prepare or reinstall the complete SDK.")
      endif()
    endforeach()
    if(SYMBIAN_NATIVE_FIRMWARE_DIR)
      file(GLOB firmware_dlls "${SYMBIAN_NATIVE_FIRMWARE_DIR}/sys/bin/*"
        "${SYMBIAN_NATIVE_FIRMWARE_DIR}/Sys/Bin/*")
      set(found FALSE)
      foreach(file IN LISTS firmware_dlls)
        get_filename_component(filename "${file}" NAME)
        string(TOLOWER "${filename}" filename)
        if(filename STREQUAL dll)
          set(found TRUE)
          set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${file}")
        endif()
      endforeach()
      if(NOT found)
        message(FATAL_ERROR "${target}: Symbian::${api} is unavailable in selected firmware: ${dll} is absent from the complete Z-drive ${SYMBIAN_NATIVE_FIRMWARE_DIR}. Leave firmware compatibility unknown when no complete Z-drive is available.")
      endif()
    endif()
  endforeach()
  if(NOT apis)
    return()
  endif()
  get_property(conditional GLOBAL PROPERTY SYMBIAN_GRAPHICS_CONDITIONAL)
  if(conditional)
    message(FATAL_ERROR "${target}: native SDK graph uses unsupported conditional links: ${conditional}. Select dependencies with CMake if() for configuration-time validation.")
  endif()
  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Generic" OR
      NOT SYMBIAN_TARGET_ARCH MATCHES "^(armv5t|armv6)$" OR
      NOT CMAKE_CXX_COMPILER_TARGET STREQUAL "${SYMBIAN_TARGET_ARCH}-none-eabi")
    message(FATAL_ERROR "${target}: native frozen interfaces require the Symbian ARM EABI toolchain (armv5t or armv6)")
  endif()
  set(options "${CMAKE_C_FLAGS};${CMAKE_CXX_FLAGS};${CMAKE_EXE_LINKER_FLAGS};${CMAKE_SHARED_LINKER_FLAGS}")
  foreach(config IN ITEMS DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
    list(APPEND options "${CMAKE_C_FLAGS_${config}}" "${CMAKE_CXX_FLAGS_${config}}"
      "${CMAKE_EXE_LINKER_FLAGS_${config}}" "${CMAKE_SHARED_LINKER_FLAGS_${config}}")
  endforeach()
  foreach(node IN LISTS nodes)
    get_target_property(kernel ${node} SYMBIAN_IMAGE_KERNEL)
    if(kernel STREQUAL "eka1")
      message(FATAL_ERROR "${target}: selected public native imports are EKA2 interfaces; use the separate EKA1 profile")
    endif()
    foreach(property COMPILE_OPTIONS INTERFACE_COMPILE_OPTIONS LINK_OPTIONS
        INTERFACE_LINK_OPTIONS COMPILE_DEFINITIONS INTERFACE_COMPILE_DEFINITIONS
        COMPILE_FLAGS LINK_FLAGS)
      get_target_property(value ${node} ${property})
      list(APPEND options ${value})
    endforeach()
    get_target_property(sources ${node} SOURCES)
    get_target_property(directory ${node} SOURCE_DIR)
    foreach(source IN LISTS sources)
      if(NOT source MATCHES "\\$<")
        foreach(property COMPILE_OPTIONS COMPILE_FLAGS COMPILE_DEFINITIONS)
          get_source_file_property(value "${source}" DIRECTORY "${directory}" ${property})
          list(APPEND options ${value})
        endforeach()
      endif()
    endforeach()
  endforeach()
  string(REGEX MATCHALL "-mfpu[= ][A-Za-z0-9_.+-]+" fpu_flags "${options}")
  foreach(flag IN LISTS fpu_flags)
    if(NOT flag MATCHES "-mfpu[= ]none$")
      message(FATAL_ERROR "${target}: native SDK requires software floating point; incompatible FPU flag ${flag}")
    endif()
  endforeach()
  string(REGEX MATCHALL "-march[= ][A-Za-z0-9_.+-]+" flags "${options}")
  foreach(flag IN LISTS flags)
    string(REGEX REPLACE "^-march[= ]" "" architecture "${flag}")
    if(NOT architecture STREQUAL SYMBIAN_TARGET_ARCH)
      message(FATAL_ERROR "${target}: native SDK architecture flag ${flag} conflicts with ${SYMBIAN_TARGET_ARCH}")
    endif()
  endforeach()
  if("${options}" MATCHES "-mfloat-abi[= ](hard|softfp)|-mabi[= ](apcs-gnu|aapcs-vfp)|-fno-short-wchar|-mcpu[= ]")
    message(FATAL_ERROR "${target}: native SDK requires soft-float AAPCS, 16-bit wchar_t and the selected SDK architecture; incompatible flags: ${options}")
  endif()
endfunction()

function(_symbian_validate_native_directory directory)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  foreach(target IN LISTS targets)
    _symbian_validate_native(${target})
  endforeach()
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    _symbian_validate_native_directory("${child}")
  endforeach()
endfunction()
cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}"
  CALL _symbian_validate_native_directory "${CMAKE_SOURCE_DIR}")
