# Original LGPL Qt Mobility 1.0.3 public interfaces and frozen ordinals.
include_guard(GLOBAL)
set(mobility_inventory
  "${SYMBIAN_SDK_PREFIX}/share/symbian/qtmobility/inventory.json")
if(NOT EXISTS "${mobility_inventory}")
  return()
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
  "${mobility_inventory}")
file(READ "${mobility_inventory}" mobility_surface)
string(JSON count LENGTH "${mobility_surface}" modules)
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
  string(JSON entry GET "${mobility_surface}" modules ${index})
  string(JSON api GET "${entry}" target)
  string(REGEX REPLACE "^Symbian::QtMobility" "" name "${api}")
  string(JSON dll GET "${entry}" dll)
  string(REGEX REPLACE "\\.dll$" "" basename "${dll}")
  set(proxy "${SYMBIAN_SDK_PREFIX}/proxies/${basename}/${basename}.dso")
  add_library(SymbianQtMobility${name} SHARED IMPORTED GLOBAL)
  add_library(${api} ALIAS SymbianQtMobility${name})
  set_target_properties(SymbianQtMobility${name} PROPERTIES
    IMPORTED_LOCATION "${proxy}"
    SYMBIAN_QTMOBILITY_API "${api}"
    SYMBIAN_QTMOBILITY_ENTRY "${entry}")
  target_include_directories(SymbianQtMobility${name} SYSTEM INTERFACE
    "${SYMBIAN_SDK_PREFIX}/include/qtmobility"
    "${SYMBIAN_SDK_PREFIX}/include/qtmobility/Qt${name}")
  string(JSON dependencies LENGTH "${entry}" dependencies)
  if(dependencies GREATER 0)
    math(EXPR dep_last "${dependencies} - 1")
    foreach(dep RANGE 0 ${dep_last})
      string(JSON dependency GET "${entry}" dependencies ${dep})
      target_link_libraries(SymbianQtMobility${name} INTERFACE ${dependency})
    endforeach()
  endif()
endforeach()

function(_symbian_validate_qtmobility target)
  get_target_property(own_api ${target} SYMBIAN_QTMOBILITY_API)
  if(own_api)
    return()
  endif()
  set_property(GLOBAL PROPERTY SYMBIAN_GRAPHICS_WALK "")
  set_property(GLOBAL PROPERTY SYMBIAN_GRAPHICS_CONDITIONAL "")
  _symbian_graphics_walk(${target} ROOT)
  get_property(nodes GLOBAL PROPERTY SYMBIAN_GRAPHICS_WALK)
  set(selected)
  foreach(node IN LISTS nodes)
    get_target_property(api ${node} SYMBIAN_QTMOBILITY_API)
    if(NOT api)
      continue()
    endif()
    list(APPEND selected "${api}")
    get_target_property(entry ${node} SYMBIAN_QTMOBILITY_ENTRY)
    string(JSON dll GET "${entry}" dll)
    string(REGEX REPLACE "\\.dll$" "" basename "${dll}")
    set(required
      "${SYMBIAN_SDK_PREFIX}/proxies/${basename}/${basename}.dso"
      "${SYMBIAN_SDK_PREFIX}/include/qtmobility/qmobilityglobal.h")
    string(JSON definition GET "${entry}" definition)
    get_filename_component(definition_name "${definition}" NAME)
    list(APPEND required
      "${SYMBIAN_SDK_PREFIX}/share/symbian/qtmobility/defs/${definition_name}")
    string(JSON header_count LENGTH "${entry}" headers)
    math(EXPR header_last "${header_count} - 1")
    foreach(index RANGE 0 ${header_last})
      string(JSON spelling GET "${entry}" headers ${index} include)
      list(APPEND required
        "${SYMBIAN_SDK_PREFIX}/include/qtmobility/${spelling}")
    endforeach()
    string(JSON alias_count LENGTH "${entry}" aliases)
    if(alias_count GREATER 0)
      math(EXPR alias_last "${alias_count} - 1")
      foreach(index RANGE 0 ${alias_last})
        string(JSON spelling GET "${entry}" aliases ${index} include)
        list(APPEND required
          "${SYMBIAN_SDK_PREFIX}/include/qtmobility/${spelling}")
      endforeach()
    endif()
    foreach(file IN LISTS required)
      if(NOT EXISTS "${file}")
        message(FATAL_ERROR "${target}: ${api} missing SDK payload ${file}; reinstall the complete Qt Mobility extension")
      endif()
    endforeach()
    if(SYMBIAN_NATIVE_FIRMWARE_DIR)
      file(GLOB firmware_dlls "${SYMBIAN_NATIVE_FIRMWARE_DIR}/sys/bin/*"
        "${SYMBIAN_NATIVE_FIRMWARE_DIR}/Sys/Bin/*")
      set(found FALSE)
      foreach(file IN LISTS firmware_dlls)
        get_filename_component(filename "${file}" NAME)
        string(TOLOWER "${filename}" filename)
        if(filename STREQUAL dll)
          set(found TRUE)
        endif()
      endforeach()
      if(NOT found)
        message(FATAL_ERROR "${target}: ${api} requires ${dll}, absent from the selected complete firmware Z-drive")
      endif()
    endif()
  endforeach()
  if(NOT selected)
    return()
  endif()
  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Generic" OR
      NOT SYMBIAN_TARGET_ARCH MATCHES "^(armv5t|armv6)$" OR
      NOT CMAKE_CXX_COMPILER_TARGET STREQUAL "${SYMBIAN_TARGET_ARCH}-none-eabi")
    message(FATAL_ERROR "${target}: Qt Mobility frozen imports require the Symbian EKA2 ARM EABI toolchain")
  endif()
  get_property(conditional GLOBAL PROPERTY SYMBIAN_GRAPHICS_CONDITIONAL)
  if(conditional)
    message(FATAL_ERROR "${target}: Qt Mobility imports need concrete CMake dependency links: ${conditional}")
  endif()
  set(options "${CMAKE_C_FLAGS};${CMAKE_CXX_FLAGS};${CMAKE_EXE_LINKER_FLAGS};${CMAKE_SHARED_LINKER_FLAGS}")
  set(configs Debug Release RelWithDebInfo MinSizeRel ${CMAKE_CONFIGURATION_TYPES} ${CMAKE_BUILD_TYPE})
  foreach(config IN LISTS configs)
    string(TOUPPER "${config}" config)
    list(APPEND options "${CMAKE_C_FLAGS_${config}}" "${CMAKE_CXX_FLAGS_${config}}"
      "${CMAKE_EXE_LINKER_FLAGS_${config}}" "${CMAKE_SHARED_LINKER_FLAGS_${config}}")
  endforeach()
  foreach(node IN LISTS nodes)
    get_target_property(kernel ${node} SYMBIAN_IMAGE_KERNEL)
    if(kernel STREQUAL "eka1")
      message(FATAL_ERROR "${target}: Qt Mobility imports require EKA2")
    endif()
    foreach(property COMPILE_OPTIONS INTERFACE_COMPILE_OPTIONS LINK_OPTIONS
        INTERFACE_LINK_OPTIONS COMPILE_DEFINITIONS INTERFACE_COMPILE_DEFINITIONS
        COMPILE_FLAGS LINK_FLAGS)
      get_target_property(value ${node} ${property})
      list(APPEND options ${value})
    endforeach()
    get_target_property(sources ${node} SOURCES)
    get_target_property(directory ${node} SOURCE_DIR)
    foreach(source IN LISTS sources)
      if(NOT source MATCHES "\\$<")
        foreach(property COMPILE_OPTIONS COMPILE_FLAGS COMPILE_DEFINITIONS)
          get_source_file_property(value "${source}" DIRECTORY "${directory}" ${property})
          list(APPEND options ${value})
        endforeach()
      endif()
    endforeach()
  endforeach()
  string(REGEX MATCHALL "-march[= ][A-Za-z0-9_.+-]+" architecture_flags "${options}")
  foreach(flag IN LISTS architecture_flags)
    string(REGEX REPLACE "^-march[= ]" "" architecture "${flag}")
    if(NOT architecture STREQUAL SYMBIAN_TARGET_ARCH)
      message(FATAL_ERROR "${target}: Qt Mobility architecture flag ${flag} conflicts with SYMBIAN_TARGET_ARCH=${SYMBIAN_TARGET_ARCH}")
    endif()
  endforeach()
  if("${options}" MATCHES "-mcpu[= ]")
    message(FATAL_ERROR "${target}: Qt Mobility CPU overrides are unavailable; select SYMBIAN_TARGET_ARCH")
  endif()
  string(REGEX MATCHALL "-mfpu[= ][A-Za-z0-9_.+-]+" fpu_flags "${options}")
  foreach(flag IN LISTS fpu_flags)
    if(NOT flag MATCHES "-mfpu[= ]none$")
      message(FATAL_ERROR "${target}: Qt Mobility requires software floating point; incompatible flags: ${options}")
    endif()
  endforeach()
  if("${options}" MATCHES "-mfloat-abi[= ](hard|softfp)|-mabi[= ](apcs-gnu|aapcs-vfp)|-fno-short-wchar")
    message(FATAL_ERROR "${target}: Qt Mobility requires soft-float AAPCS and 16-bit wchar_t; incompatible flags: ${options}")
  endif()
endfunction()

function(_symbian_validate_qtmobility_directory directory)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  foreach(target IN LISTS targets)
    _symbian_validate_qtmobility(${target})
  endforeach()
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    _symbian_validate_qtmobility_directory("${child}")
  endforeach()
endfunction()
cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}"
  CALL _symbian_validate_qtmobility_directory "${CMAKE_SOURCE_DIR}")
