# Shared SDK selection for installed applications and source workspaces.
function(symbian_select_sdk)
  set(selection_directory "${CMAKE_CURRENT_SOURCE_DIR}")
  if(ARGC GREATER 0)
    get_filename_component(selection_directory "${ARGV0}" ABSOLUTE
      BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  endif()
  set(location "${selection_directory}/sdk-location.json")
  if(EXISTS "${location}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${location}")
    file(READ "${location}" selection)
    string(JSON prefix GET "${selection}" sdk)
    get_filename_component(prefix "${prefix}" ABSOLUTE
      BASE_DIR "${selection_directory}")
  elseif(SYMBIAN_SDK_PREFIX AND NOT SYMBIAN_USE_ACTIVE_SDK)
    set(prefix "${SYMBIAN_SDK_PREFIX}")
  elseif(DEFINED ENV{SYMBIAN_SDK_MANIFEST})
    get_filename_component(prefix "$ENV{SYMBIAN_SDK_MANIFEST}" DIRECTORY)
  else()
    if(DEFINED ENV{XDG_CONFIG_HOME})
      set(active "$ENV{XDG_CONFIG_HOME}/symbian/active-sdk.json")
    else()
      set(active "$ENV{HOME}/.config/symbian/active-sdk.json")
    endif()
    if(EXISTS "${active}")
      set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${active}")
      file(READ "${active}" selection)
      string(JSON manifest GET "${selection}" manifest)
      get_filename_component(prefix "${manifest}" DIRECTORY)
    endif()
  endif()
  if(prefix)
    set(SYMBIAN_SDK_PREFIX "${prefix}" PARENT_SCOPE)
  endif()
endfunction()

# A mixed host/guest workspace scopes its ARM toolchain to this directory.
# Application CMakeLists remain identical to their standalone form.
function(symbian_add_guest_subdirectory directory)
  symbian_select_sdk("${directory}")
  if(NOT EXISTS "${SYMBIAN_SDK_PREFIX}/cmake/SymbianApp.cmake")
    message(FATAL_ERROR "Install a native SDK with symbian sdk install")
  endif()
  if(NOT SYMBIAN_TARGET_ARCH)
    set(SYMBIAN_TARGET_ARCH armv6)
  endif()
  set(SYMBIAN_WORKSPACE_BUILD ON)
  include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/symbian-arm.cmake")
  string(REPLACE "<CMAKE_LINKER>" "\"${CMAKE_LINKER}\""
    CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_CXX_LINK_EXECUTABLE}")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS_INIT}")
  set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS_INIT}")
  set(CMAKE_CXX_LINK_FLAGS "")
  set(CMAKE_SKIP_RPATH ON)
  set(CMAKE_OSX_ARCHITECTURES "")
  set(CMAKE_OSX_SYSROOT "")
  set(CMAKE_OSX_DEPLOYMENT_TARGET "")
  # Source workspaces use their maintained CMake definitions with SDK binaries.
  set(application_modules "${SYMBIAN_SDK_PREFIX}/cmake")
  if(EXISTS "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../project/templates/SymbianApp.cmake")
    set(application_modules
      "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../project/templates")
  endif()
  list(PREPEND CMAKE_MODULE_PATH "${application_modules}"
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}")
  include(SymbianApp)
  enable_language(ASM)
  add_subdirectory("${directory}" EXCLUDE_FROM_ALL)
  # Publish the project's primary application beside its ELF in host workspaces.
  # Identity remains in the same project configuration used by the CLI.
  if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${directory}/symbian.toml")
    file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/${directory}/symbian.toml" name
      REGEX "^name[ \t]*=[ \t]*\"[A-Za-z][A-Za-z0-9_-]*\"[ \t]*$")
    file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/${directory}/symbian.toml" uid
      REGEX "^uid3[ \t]*=[ \t]*0x[0-9A-Fa-f]+[ \t]*$")
    if(name AND uid)
      list(GET name 0 name)
      list(GET uid 0 uid)
      string(REGEX REPLACE "^name[ \t]*=[ \t]*\"([^\"]+)\"[ \t]*$" "\\1" name "${name}")
      string(REGEX REPLACE "^uid3[ \t]*=[ \t]*" "" uid "${uid}")
      if(TARGET "${name}" AND NOT TARGET "${name}_e32")
        symbian_publish_executable(${name} UID3 "${uid}")
      endif()
    endif()
  endif()
endfunction()
