[project]
name = "gui_app"
kind = "e32-import-experiment"
cmake_preset = "symbian-pic"
uid3 = 0xe0000811
import_proxies = [
  "../../.symbian/gui-sdk/euser/euser.dso",
  "../../.symbian/gui-sdk/ws32/ws32.dso",
]

[package]
uid = 0xe0000812
name = "Symbian GUI Counter"
vendor = "Symbian research"
executable_name = "gui_app.exe"
version = [1, 0, 0]
