add_library(symbian_agent_frame STATIC frame.cc control.cc guest_control.cc)
add_library(symbian::agent_frame ALIAS symbian_agent_frame)
target_include_directories(symbian_agent_frame PUBLIC ${PROJECT_SOURCE_DIR}/cpp)
target_link_libraries(symbian_agent_frame PUBLIC symbian::status absl::statusor)
symbian_native_library(symbian_agent_frame)
