cmake_minimum_required(VERSION 3.28)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  project(zlib_app_classic LANGUAGES C CXX ASM)
endif()
include(SymbianApp)
symbian_add_executable(zlib_app_classic main.cc ui.cc)
target_link_libraries(zlib_app_classic PRIVATE Symbian::WindowServer Symbian::Gdi)
target_link_libraries(zlib_app_classic PRIVATE Symbian::PortableZlib)
symbian_publish_executable(zlib_app_classic UID3 0xe0000e12)
