[project]
name = "png_app_classic"
kind = "e32-import"
architecture = "armv6"
cmake_preset = "symbian-pic"
uid3 = 0xe0000e13

[package]
uid = 0xe0000f13
name = "Symbian Portable PNG Classic"
vendor = "Symbian SDK examples"
executable_name = "png_app_classic.exe"
version = [1, 0, 0]
