"""Read a selected application's declared identity and local build state."""

import tomllib
import xml.etree.ElementTree as ET
from base64 import b64encode
from pathlib import Path

from pydantic import Field

from symbian.console.models import ConsoleModel
from symbian.status import Code, Status, StatusException
from symbian.toolchain.architecture import project_architecture


class ApplicationOverview(ConsoleModel):
    """Small, read-only summary of one application directory."""

    directory: str = Field(description="Absolute application source directory")
    name: str = Field(description="CMake target and executable base name")
    caption: str = Field(description="Visible application caption")
    architecture: str = Field(description="Declared ARM target architecture")
    uid3: str = Field(description="Executable UID3 in hexadecimal notation")
    kind: str = Field(description="Declared native target kind")
    package_name: str | None = Field(
        default=None,
        description="SIS package display name, when declared",
        exclude_if=lambda value: value is None,
    )
    artifact: str | None = Field(
        default=None,
        description="Existing E32 executable that can be packaged",
        exclude_if=lambda value: value is None,
    )
    generated: bool = Field(
        default=False,
        description="Whether SDK project settings were generated by init",
        exclude_if=lambda value: not value,
    )
    firmware: str | None = Field(
        default=None,
        description="Currently resolved emulator firmware reference",
        exclude_if=lambda value: value is None,
    )
    icon_data_url: str | None = Field(
        default=None,
        description="Bounded local project icon safe for an image element",
        exclude_if=lambda value: value is None,
    )


_SVG_ELEMENTS = {
    "svg",
    "g",
    "rect",
    "path",
    "circle",
    "ellipse",
    "line",
    "polygon",
    "polyline",
}
_SVG_ATTRIBUTES = {
    "xmlns",
    "viewBox",
    "width",
    "height",
    "x",
    "y",
    "x1",
    "y1",
    "x2",
    "y2",
    "cx",
    "cy",
    "r",
    "rx",
    "ry",
    "d",
    "points",
    "transform",
    "fill",
    "stroke",
    "stroke-width",
    "stroke-linecap",
    "stroke-linejoin",
    "opacity",
    "fill-rule",
}


def _project_icon(directory: Path, declared: object) -> str | None:
    """Embed only small project-local static image content."""
    if not isinstance(declared, str) or not declared:
        return None
    path = (directory / declared).resolve()
    if not path.is_relative_to(directory) or not path.is_file():
        return None
    if path.stat().st_size > 256 * 1024:
        return None
    data = path.read_bytes()
    media_type = None
    if path.suffix.lower() == ".svg":
        try:
            root = ET.fromstring(data)
        except ET.ParseError:
            return None
        if root.tag != "{http://www.w3.org/2000/svg}svg":
            return None
        for element in root.iter():
            if element.tag.rsplit("}", 1)[-1] not in _SVG_ELEMENTS:
                return None
            if any(
                key.rsplit("}", 1)[-1] not in _SVG_ATTRIBUTES
                or "url(" in value.lower()
                or "javascript:" in value.lower()
                for key, value in element.attrib.items()
            ):
                return None
        data = ET.tostring(root, encoding="utf-8")
        media_type = "image/svg+xml"
    elif data.startswith(b"\x89PNG\r\n\x1a\n"):
        media_type = "image/png"
    elif data.startswith(b"\xff\xd8\xff"):
        media_type = "image/jpeg"
    if media_type is None:
        return None
    return f"data:{media_type};base64,{b64encode(data).decode('ascii')}"


def read_application(
    directory: Path, firmware: str | None = None
) -> ApplicationOverview:
    """Read declared fields without assuming that a build has succeeded."""
    directory = directory.expanduser().resolve()
    manifest = directory / "symbian.toml"
    try:
        if manifest.stat().st_size > 1024 * 1024:
            raise ValueError("Application manifest is too large")
        content = tomllib.loads(manifest.read_text(encoding="utf-8"))
        project = content["project"]
        name = project["name"]
        kind = project["kind"]
        uid3 = project["uid3"]
        if (
            not isinstance(name, str)
            or not isinstance(kind, str)
            or type(uid3) is not int
        ):
            raise ValueError("Invalid application identity")
        package = content.get("package", {})
        application = content.get("application", {})
        artifact = directory / ".symbian/build" / f"{name}.exe"
        try:
            architecture = project_architecture(
                directory, project, project.get("cmake_preset", "symbian-pic")
            )
        except (OSError, StatusException, ValueError, KeyError, TypeError):
            architecture = "Unknown"
        return ApplicationOverview(
            directory=str(directory),
            name=name,
            caption=str(
                application.get("caption") or package.get("name") or name
            ),
            architecture=architecture,
            uid3=f"0x{uid3:08x}",
            kind=kind,
            package_name=package.get("name"),
            artifact=str(artifact) if artifact.is_file() else None,
            generated=(directory / "symbian-project.json").is_file(),
            firmware=firmware,
            icon_data_url=_project_icon(directory, application.get("icon")),
        )
    except (OSError, UnicodeError, ValueError, KeyError, TypeError) as error:
        raise Status(
            code=Code.INVALID_ARGUMENT,
            message=f"Could not read application at {directory}: {error}",
        ).to_exception() from error
