add_library(symbian_websocket STATIC websocket.cc)
target_include_directories(symbian_websocket PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/../..")
target_compile_features(symbian_websocket PUBLIC cxx_std_20)
target_compile_options(symbian_websocket PRIVATE -fno-exceptions)
target_link_libraries(symbian_websocket PUBLIC symbian_http)
if(TARGET Symbian::AbseilStatusOr)
  target_link_libraries(symbian_websocket PUBLIC Symbian::AbseilStatusOr)
  target_compile_options(symbian_websocket PRIVATE -fno-pic)
else()
  target_link_libraries(symbian_websocket PUBLIC absl::statusor)
  symbian_native_library(symbian_websocket)
endif()
