add_library(symbian_http STATIC types.cc http1.cc http2.cc connection.cc)
target_include_directories(symbian_http PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/../..")
target_compile_features(symbian_http PUBLIC cxx_std_20)
target_compile_options(symbian_http PRIVATE -fno-exceptions)
target_link_libraries(symbian_http PUBLIC symbian_nghttp2)
if(TARGET Symbian::AbseilStatusOr)
  target_link_libraries(symbian_http PUBLIC Symbian::AbseilStatusOr)
  target_compile_options(symbian_http PRIVATE -fno-pic)
else()
  target_link_libraries(symbian_http PUBLIC absl::statusor absl::time)
  symbian_native_library(symbian_http)
endif()
