set(SYMBIAN_NATIVE_EXAMPLES
  audio_app_classic bitmap_app_classic image_app_classic vibra_app_classic
  linking_app openc_app_classic apparc_app_classic qt_modules_app_classic
  qt_mobility_app_classic)
